### ISSUE TITLE
Cannot localize on different resolution than 0.05

### ISSUE THREAD

**Issue by tonaaskarwur** [NVIDIA-ISAAC-ROS/isaac_ros_map_localization#6]
I have been trying occupancy_grid_localizer and it worked properly using a map with 0.05 resolution.
However, when I use different values for the map resolution (0.01), occupancy_grid_localizer will show up error logs:

ERROR packages/flatscan_localization/gems/multi_trace_and_match/cuda_kernels.cu.cpp@194: CUDA ERROR: an illegal memory access was encountered

The localizer service will still kick in and move the robot pose to random points outside the map.
My system setup is using Orin and ROS2 Humble Docker from isaac_common_ros, but with a physical robot and my own custom bringup system.
I made map using slam_toolbox with 0.01 resolution and passed the same map data to occupancy_grid_localizer.

**Comment by jaiveersinghNV** [comment]
Could you provide the launch file and full logs for the run with 0.01 resolution? Additionally, what were the input image dimensions?

Which Orin system is this running on? AGX Orin 64GB/32GB, Orin NX 16GB/8GB, Orin Nano 8GB/4GB?

**Comment by tonaaskarwur** [comment]
My system is running on AGX Orin Dev Kit using docker ROS2 humble from [isaac_ros_common](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common). I have a custom differential AGV type robot with a bringup launch (lidar, wheel, etc) and navigation bringup launcher which works fine.
I did mapping using [slam_toolbox](https://github.com/SteveMacenski/slam_toolbox/blob/ros2/launch/offline_launch.py) to get a map of 0.01 resolution. The output map is in .pgm where I then convert it to .png
Since I am using only laserscan data, I launched the [converter launch](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_map_localization/blob/main/isaac_ros_pointcloud_utils/launch/isaac_ros_laserscan_to_flatscan.launch.py) to get flatscan.
Then, I launched the [grid localizer](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_map_localization/blob/main/isaac_ros_occupancy_grid_localizer/launch/isaac_ros_occupancy_grid_localizer.launch.py) which goes to my custom map with 0.01 resolution from the mapping session before.
Last, I called the ros2 service localizer.
The logs showing from grid localizer and ros2 service localizer terminals are attached.
Thank you

[localizer_debug.txt](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_map_localization/files/11482802/localizer_debug.txt)

**Comment by ashwinvkNV** [comment]
Hi, can you please upload a **short rosbag** of your LaserScan or FlatScan msgs. And also upload the **map (.png+.yaml file)** you used?

**Comment by tonaaskarwur** [comment]
[debug_localizer.zip](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_map_localization/files/11493181/debug_localizer.zip)
I zipped a rosbag topics of /base_scan (my original laser_scan), /flatscan, /initialpose, /flatscan_localization.
You can find the .png and yaml that I used for the localizer in the zipped file too.
Thank you

**Comment by ashwinvkNV** [comment]
I am to reproduce the error. But I am able to us the data that you uploaded and was able to get localization outputs for the following resolutions:

**Comment by ashwinvkNV** [comment]
Hi, this was a bug in the core library. The bug has been fixed with these binary updates. https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nitros/pull/23

Can you please verify that the issue has been fixed after pulling the latest main branch of [isaac_ros_nitros](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nitros)?

**Comment by tonaaskarwur** [comment]
I tried pulling the latest main branch of isaac_ros_nitros, and recompiled everything.
The same error is still showing in my setup, showing this in the [localizer launch terminal](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_map_localization/blob/main/isaac_ros_occupancy_grid_localizer/launch/isaac_ros_occupancy_grid_localizer.launch.py):

ERROR packages/flatscan_localization/gems/multi_trace_and_match/cuda_kernels.cu.cpp@194: CUDA ERROR: an illegal memory access was encountered

I also tried to pull the latest main branch of isaac_ros_map_localization, but still it doesn't work for 0.01 resolution.
However it is working for 0.05. Note that I deleted the whole /install and /build files before recompiling.
